services:
  aqua-gas-monitor:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - 'db'
  db:
    image: postgres
    container_name: aquagas-db
    restart: always
    tty: true
    environment:
      POSTGRES_DB: aquagas
      POSTGRES_USER: aqua
      POSTGRES_PASSWORD: gas
      PGDATA: /var/lib/postgresql/data/
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - docker-aqua-gas:/var/lib/postgresql/data/:rw

volumes:
  docker-aqua-gas:
