services:
  aqua-gas-monitor:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    environment:
      POSTGRES_DB: aquagas
      POSTGRES_USER: aqua
      POSTGRES_PASSWORD: gas
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - docker-aqua-gas:/var/lib/postgresql/data/:rw
  db-migration:
    build: .
    depends_on:
      - "aqua-gas-monitor"
      - "db"
    environment:
      DATABASE_URL: postgresql://aqua:gas@db:5432/aquagas
    command: bash -c './wait-for-it.sh -h db -p 5432 && npx prisma migrate dev'

volumes:
  docker-aqua-gas: